// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY5NdcB3LtwHKHNnf-e5TIygJ6BKSVqb4',
    appId: '1:1059383809484:android:862a4b0e27fa437973b969',
    messagingSenderId: '1059383809484',
    projectId: 'projet3-equipe106',
    databaseURL: 'https://projet3-equipe106-default-rtdb.firebaseio.com',
    storageBucket: 'projet3-equipe106.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCZnDTs5GnLKvcijB9jIUPi_kGzYzQRr4',
    appId: '1:1059383809484:ios:24cdb5d64cb174fd73b969',
    messagingSenderId: '1059383809484',
    projectId: 'projet3-equipe106',
    databaseURL: 'https://projet3-equipe106-default-rtdb.firebaseio.com',
    storageBucket: 'projet3-equipe106.appspot.com',
    iosClientId:
        '1059383809484-05kkfl61o2p9ic8r8rsjrpat94r3g9mn.apps.googleusercontent.com',
    iosBundleId: 'com.example.clientLeger',
  );
}
